# Generated by Django 3.1 on 2020-08-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpostsmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
