<<<<<<< HEAD:posts/migrations/0002_auto_20200831_1229.py
# Generated by Django 3.1 on 2020-08-31 09:29
=======
# Generated by Django 3.1 on 2020-08-30 18:37
>>>>>>> 8d125ebce00742fa4994f5061f88d884632d703b:posts/migrations/0002_auto_20200830_2137.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименования')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Публикация')),
                ('photo', models.ImageField(blank=True, upload_to='media/photos/%Y/%m/%d/', verbose_name='Фото')),
                ('is_published', models.BooleanField(default=True, verbose_name='Состояние')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-created_at', '-title'],
            },
        ),
        migrations.DeleteModel(
            name='CreatePostsModel',
        ),
    ]
