# Generated by Django 3.1 on 2020-08-31 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200830_2002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostsModel',
            new_name='Post',
        ),
    ]
