# Generated by Django 3.1 on 2020-08-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200824_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createpostsmodel',
            options={'ordering': ['-created_at', '-title'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
