# Generated by Django 3.0.8 on 2020-08-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
