# Generated by Django 3.1.1 on 2020-09-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200903_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='media/avatar/%Y/%m/%d/', verbose_name='Аватар'),
        ),
    ]
