# Generated by Django 3.0.8 on 2020-08-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200805_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
