# Generated by Django 3.1.1 on 2020-09-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200922_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='media/profile/%Y/%m/%d/', verbose_name='Аватар'),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
