# Generated by Django 3.1 on 2020-08-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage-app', '0002_auto_20200821_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='comment',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Описание'),
        ),
    ]
