# Generated by Django 3.1 on 2020-08-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage-app', '0003_auto_20200823_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер дела'),
        ),
    ]
