# Generated by Django 3.1 on 2020-08-23 15:19

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage-app', '0004_auto_20200823_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/files/%Y/%m/%d'), upload_to='', verbose_name='Файлы'),
        ),
    ]
