# Generated by Django 3.1 on 2020-08-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage-app', '0006_auto_20200823_1845'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadFileModel',
            new_name='UploadFilesModel',
        ),
    ]
