# Generated by Django 3.1 on 2020-08-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage-app', '0007_auto_20200823_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilesmodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Тема вопроса'),
        ),
    ]
